name: Release
on:
  push:
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Signed APK
        uses: TeamNecta/build-signed-apk@main
        with:
          java_distribution: 'adopt'
          keystore_b64: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          key_password: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-APK
          path: app/build/outputs/apk/emf2024/release/Fahrplan-v0.9.0-emf2024-release-unsigned.apk
          retention-days: 365

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK
          path: app/build/outputs/apk/emf2024/release/Fahrplan-v0.9.0-emf2024-release-release.apk
          retention-days: 365